 variables: 
   IMAGE_NAME: fasibio/portainer-api-cli

 buildBin: 
    stage: buildBin
    only:
      - master
    tags:
      - dockerfasibio
    image: golang:1.12.8-alpine3.9
    script: 
      - apk add make
      - GO111MODULE=on CGO_ENABLED=0 GOOS=linux go build -mod vendor -a -installsuffix cgo -o portainer-api .
    cache:
      paths:
        - portainer-api

 buildImageMaster: 
    stage: buildImage
    only:
      - master
    tags:
      - dockerfasibio
    image: docker
    cache:
      paths:
        - portainer-api
    script: 
     - docker build -t ${IMAGE_NAME}:latest .

 publishMaster: 
   stage: publish
   image: docker
   only:
     - master
   tags:
     - dockerfasibio
   script: 
     - docker login -u ${dockerhubuser} -p ${dockerhubpassword}
     - docker push ${IMAGE_NAME}:latest


 stages:
   - buildBin
   - buildImage
   - publish
